services:
  - type: web
    name: signify-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
